version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet test UnitTests
      - run: dotnet build Tinygubackend
      - run: ssh-keyscan poc3.itp.uni-frankfurt.de >> ~/.ssh/known_hosts
      - run: git remote add dokku dokku@poc3.itp.uni-frankfurt.de:tinygu-staging-api
      - run: git push dokku master
