version: 2
jobs:
  build-job:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: 
          name: Running tests
          command: dotnet test UnitTests
      - run: 
          name: Trying build
          command: dotnet build Tinygubackend

  deploy-job:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: ssh-keyscan poc3.itp.uni-frankfurt.de >> ~/.ssh/known_hosts
      - run: git remote add dokku dokku@poc3.itp.uni-frankfurt.de:tinygu-staging-api
      - run: 
          name: Pushing to dokku
          command: git push dokku master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master